### ISSUE TITLE
[Feature Request] Configure a pool size of sorts?

### ISSUE THREAD

**Issue by coladarci** [conduitframework/conduit#22]
We have some situations in our stack where we want to publish a plethora of messages and have the queue *slowly* drain. Currently, if we publish let's say 100k messages, our Broker will pull off as many as it possibly can in parallel and things grind to a halt. (Imagine if each message is extremely heavy to process, we are ok if it takes an hour to drain, but it's not ok if all 500 are attempted at the same time, for CPU reasons). In fact, when this happens, we notice a separate bug that we are trying to get steps to reproduce on where messages are "stuck" in processing - we have to kill the connections holding those messages to "un stick them" so they can be handled.

If this behavior is surprising to you, we'd love to hear there's a way to stop this from happening. If not, would you be open to a PR where we write some Middleware to essentially throttle the Broker (and perhaps you could even point us in the right starting direction?).

Thanks for all your help!

**Comment by blatyo** [comment]
Yea, this is surprising. Are you using RabbitMQ? If so, you should set a `prefetch_size` or `prefetch_count`. See the docs here: https://hexdocs.pm/conduit_amqp/readme.html#configuring-a-subscriber

**Comment by coladarci** [comment]
Thank you!! Not sure how we missed that - you did a good job making that very clear in the docs. 

That said, you mention in the docs that they can both be configured globally but I can't for the life of me figure out where you'd set that. Is it a conduit setting? A conduit_amqp setting? The source code doesn't seem to be reading from an application config (that I can see, at least!).

**Comment by blatyo** [comment]
Sorry that's not clear. When it says something can be configured globally, it means it can be configured at the adapter level.

``` elixir
config :my_app, MyBroker, adapter: ConduitAMQP, url: "", prefetch_size: 20
```

Happy to take any doc improvements to make that clearer.

**Comment by coladarci** [comment]
Sorry for keeping this closed issue around, but just one last question. While this fixed the issues we were seeing, we got this feedback when trying to get this mainline in our codebase:

> This would limit the number of messages coming in from the amqp/rabbit side. This is probably the right solution, but is not compatible with the existing retry/dead-lettering middleware.
The conduit middleware for retrying does a Process.sleep/1 while holding onto the message. While a message is waiting to be retried, it will still be holding onto that message, so no new messages will be processed by a worker if there are currently 10 messages waiting to go through the entire retry looping for that worker type on that host. I have seen hundreds waiting to be retried before, so there's a real risk of starving the workers.

To be honest, when I flooded the queue w/ messages that would always fail (to mimic this concern), publishing a new message to a different subscription on the same worker DID get through, but I can't really explain why.

Are these concerns valid? (if this is the wrong place for this, happy to create a separate thread for it, but it's tightly coupled w/ this configuration, so it seemed ok here)

UPDATE: I think this was a somewhat dumb question, apologies. the cap you set is per subscription. So I just flooded one of them, and yes it was starved but that didn't stop a different subscription from pulling messages. Has there been any thought given to a dead-letter approach that doesn't keep them in memory?

**Comment by blatyo** [comment]
If you have frequent failure in processing messages, the retry plug will tie up the workers and prevent other messages from getting processed. I don't know the context in your application, but if a large number of messages are going to fail, it implies that any message being processed would fail, so it wouldn't seem to matter that the queue continue to backup because it would do so anyway. For example, if every message on a particular queue needs to make an http request to a service that's down, it doesn't matter if failed messages get out of the way, because all subsequent messages will fail.

The retry plug in conduit is designed to be a good enough solution that isn't broker specific. There may be broker specific solutions that are a better fit for your situation. That'll be something you'll have to explore on your own. I recommend checking out the docs on [TTL](https://www.rabbitmq.com/ttl.html) and [Dead Letter Exchanges](https://www.rabbitmq.com/dlx.html). If you come up with any specific plugs that make sense specifically for AMQP, I'd be happy to accept a contribution to conduit_amqp. If it just ends up configuring existing stuff in a particular way, I'd still love to know what you did.

**Comment by coladarci** [comment]
Thank you! This is helpful - I will keep you posted with where we end up..

One thing that’s bad about our current setup is we have some messages that contain bad data that hard-fail and get retried the max number of times. We can’t ignore these because we need the message but retrying with the same code base will continue to fail. We are going to look into how to skip the retry logic for certain types of failures and not others, and go straight to dead letter. This will help the large majority of our backups.
