### ISSUE TITLE
Keep a changelog

### ISSUE THREAD

**Issue by doughsay** [conduitframework/conduit#5]
Can you start keeping a changelog? (https://keepachangelog.com/)

I'm on `0.10.4` and I see `0.11.0` was released recently, but there's no (easy) way for me to see what changed and if it's safe for me to upgrade.

Thanks!

**Comment by blatyo** [comment]
Sure, I'll add one later.

For the short term, the primary things were:
1. Started formatting with the elixir formatter and added formatting stuff you can import into your project for DSL stuff that shouldn't have parens.
2. Added support for the new child spec stuff
3. The 0.11.0 change was to support being able to run more than one of the same adapter at a time. It required an adapter API change, which is the reason for the bump to 11. You should also update your adapter if you make that change. While I'm pre-1.0.0, patch level should be safe for upgrade, anything else may require some changes, but those are most likely a required adapter upgrade.

ConduitAMQP got
1. The ability to have multiple running at the same time.
2. A tweak to how it handles large binaries, which should help keep it's memory lower
3. Newer versions amqp, amqp_client, rabbit_common. Note that amqp_client and rabbit_common include a bunch of dependencies they don't use because of some odd scheme where all their packages include dependencies on all the packages that any of their packages use. So, you may need to override versions of ranch and cowboy if you're using those.

**Comment by doughsay** [comment]
Thanks a lot for the details!  I'll give the upgrade a shot tomorrow.

**Comment by blatyo** [comment]
There's a changelog now https://github.com/conduitframework/conduit/blob/master/CHANGELOG.md

**Comment by doughsay** [comment]
Awesome, thanks a lot!
